spring:
  application:
    name: Spring-Security-Jwt-Login-Register-Encrypt-Decrypt
  datasource:
    url: jdbc:mysql:///security
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          formatsql: true