spring:
  application:
    name: MicroServices-Apigateway
  cloud:
    gateway:
      routes:
      - id: AadharApi
        uri: lb://MicroServices-AadharApi
        predicates:
          Path=/aadharcard
      - id: BankApi
        uri: lb://MicroServices-BankApi
        predicates:
          Path=/details
server:
  port: 7777
eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/			