spring:
  application:
    name: RedisCache-Boot
  data:
    redis:
      url: redis-17327.c91.us-east-1-3.ec2.redns.redis-cloud.com
      port: 17327
      username: default
      password: FmFC7A8R28nZ83ER9pvfWSPEPWijK4O3

