spring:
  application:
    name: Employee-Department-Roles
  datasource:
    url: jdbc:mysql://localhost:3306/employee-management
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formatsql: true
